version: "3"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      container_name: datascience-notebook-container
      volumes:
        - /home/jupyter/work:/home/jovyan/work
      ports:
        - 8888:8888