athena:
  target: athena
  outputs:
    athena:
      type: athena
      database: awsdatacatalog
      schema: videogame_sales
      region_name: us-east-2
      threads: 4
      s3_staging_dir: s3://interlab-athena-results