version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper-nifi
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - pipeline-data-network

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper-nifi:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    networks:
      - pipeline-data-network
    volumes:
      - /nifi:/data

networks:
  pipeline-data-network:
    driver: bridge
